In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df1 = pd.read_csv("../data/raw/Youtube01-Psy.csv")

In [5]:
df1.head()

COMMENT_ID            AUTHOR  \
0  LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU         Julius NM   
1  LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A       adam riyati   
2  LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8  Evgeny Murashkin   
3          z13jhp0bxqncu512g22wvzkasxmvvzjaz04   ElNino Melendez   
4          z13fwbwp1oujthgqj04chlngpvzmtt3r3dw            GsMega   

                  DATE                                            CONTENT  \
0  2013-11-07T06:20:48  Huh, anyway check out this you[tube] channel: ...   
1  2013-11-07T12:37:15  Hey guys check out my new channel and our firs...   
2  2013-11-08T17:34:21             just for test I have to say murdev.com   
3  2013-11-09T08:28:43   me shaking my sexy ass on my channel enjoy ^_^    
4  2013-11-10T16:05:38            watch?v=vtaRGgvGtWQ   Check this out .   

   CLASS  
0      1  
1      1  
2      1  
3      1  
4      1

In [6]:
df2 = pd.read_csv("../data/raw/Youtube02-KatyPerry.csv")
df3 = pd.read_csv("../data/raw/Youtube03-LMFAO.csv")
df4 = pd.read_csv("../data/raw/Youtube04-Eminem.csv")
df5 = pd.read_csv("../data/raw/Youtube05-Shakira.csv")

In [7]:
frames = [df1,df2,df3,df4,df5]


In [8]:
df_merged = pd.concat(frames) #merging

In [9]:
df_merged.shape

(1956, 5)

In [10]:
keys = ["Psy","KatyPerry","LMFAO","Eminem","Shakira"]

In [11]:
df_with_keys = pd.concat(frames,keys=keys)


In [12]:
df_with_keys.to_csv("../data/processed/YoutubeSpamMergeddata.csv")

In [13]:
df = df_with_keys
df.size

9780

In [15]:
df.isnull().isnull().sum()   #checking for missing values

COMMENT_ID    0
AUTHOR        0
DATE          0
CONTENT       0
CLASS         0
dtype: int64

In [18]:
df_data = df[["CONTENT","CLASS"]]    #selecting content and class only

In [19]:
df_x = df_data['CONTENT']
df_y = df_data['CLASS']

In [20]:
cv = CountVectorizer()
ex = cv.fit_transform(["Great song but check this out","What is this song?"])

In [23]:
ex.toarray()

array([[1, 1, 1, 0, 1, 1, 1, 0],
       [0, 0, 0, 1, 0, 1, 1, 1]], dtype=int64)

In [24]:
cv.get_feature_names()

['but', 'check', 'great', 'is', 'out', 'song', 'this', 'what']

In [25]:
corpus = df_x
cv = CountVectorizer()
X = cv.fit_transform(corpus)

In [26]:
X.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [27]:
len(cv.get_feature_names())

4454

### Model Building

In [28]:
from sklearn.model_selection import train_test_split


In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, df_y, test_size=0.33, random_state=42)

In [30]:
# Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.9195046439628483

In [31]:
clf.predict(X_test)

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,

In [32]:
#sample prediction
comment = ["Check this out"]
vect = cv.transform(comment).toarray()
clf.predict(vect)

array([1], dtype=int64)

In [33]:
class_dict = {'ham':0,'spam':1}
if clf.predict(vect) == 1:
    print("Spam")
else:
    print("Ham")

Spam


### Persist Model to Disk

In [34]:
import pickle

In [35]:
naivebayesML = open("../model/youtube_spam_detection_model.pkl","wb")

In [36]:
pickle.dump(clf,naivebayesML)

In [37]:
naivebayesML.close()


In [38]:
# load the model

In [40]:
youtube_spam_detection_model = open("../model/youtube_spam_detection_model.pkl","rb")

In [41]:
new_model = pickle.load(youtube_spam_detection_model)

In [ ]:

# Sample Prediciton 3
comment2 = ["Hey Music Fans I really appreciate all of you,but see this song too"]
vect = cv.transform(comment2).toarray()
new_model.predict(vect)